general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock session before physical sleep trigger
    after_sleep_cmd = hyprctl dispatch dpms on  # explicitly turn display back on after waking
}

# 1. Dim the monitor screen (Optional - 5 minutes)
listener {
    timeout = 180                                 
    on-timeout = hyprctl dispatch dpms off # turn off screen
    on-resume = hyprctl dispatch dpms on  # turn on screen
}

listener {
    timeout = 200
    on-timeout = loginctl lock-session
}

# 2. System Suspend Block (The duration and mode you want to control)
listener {
    timeout = 300                                 # 10 minutes (600 seconds)
    on-timeout = systemctl suspend-then-hibernate               # Trigger mode (suspend, hibernate, etc.)
}
